kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-1-nginx
  namespace: ns-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-deployment-6r 
  template:
    metadata:
      labels:
        app: nginx-deployment-6r 
    spec:
      containers:
        - name: nginx-app-container
          image: nginx/latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 120m
              memory: 150Mi
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
      restartPolicy: Always
      



