kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: dep-2-volumemouting
  namespace: nspace-1
  labels:
    app: group-1
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector: 
    matchLabels:
      app: podtemp--debianslim-cont
  template:
    metadata:
      name: podtemp-debain
      labels:
        app: podtemp--debianslim-cont
    spec:
      containers:
      - name: debianslim-cont
        image: debian:latest
        command:
        - sh 
        - -c 
        - > 
          mkdir -p /tmp/kind/ ;
          cp /etc/hostname /tmp/kind/ ;
          while true; do sleep 3600; done
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 120Mi
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - mountPath: /tmp/kind/
          name: volume-for-kind-debian
      volumes:
        - name: volume-for-kind-debian
          persistentVolumeClaim: 
            claimName: vol-1-pvc
