# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-1
  namespace: namespace-1
  # labels:
  #   app: myjob
spec:
  replicas: 4
  selector:
    matchLabels:                  # G:  SELECTOR -> Temp_late
      app: label-nginx
  template:                       # Y: Template => POD
    metadata:
      labels:                     # B: TEMP_LATE
        app: label-nginx
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        # imagePullPolicy: 
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 100m
            memory: 200Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: myjob
        #       key: DB_HOST
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https

      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
---

